### ISSUE TITLE
1.17 Support

### ISSUE THREAD

**Issue by vaporvee** [danjono/InventoryRollback#55]
The /ir command doesn't work at all

**Comment by Sidpatchy** [comment]
Can you provide a copy of the error generated when you run /ir? I haven't been able to reproduce this.

**Comment by vaporvee** [comment]
No it just doesn't open the UI in Minecraft

**Comment by Sidpatchy** [comment]
To me it sounds like you've got incorrect command syntax. Could you please post the exact command you're running (feel free replace the username with something else).
