### ISSUE TITLE
inventory roll back not working on 1.18 paper r3

### ISSUE THREAD

**Issue by orang3i** [danjono/InventoryRollback#59]

**Comment by orang3i** [comment]
with the new paper experimental server ir loads up but no buttons on gui wor

https://user-images.githubusercontent.com/86411355/143902673-5d0e9559-9f06-454d-ac4f-846bf6472543.mp4

**Comment by orang3i** [comment]
https://kennytv.eu/Paperclip-1.18-rc3-R0.1-EXPERIMENTAL-3.jar 

paper jar i used

**Comment by kalebchoi** [comment]
This project seems to be abandoned. However, there is an updated fork available [here](https://www.spigotmc.org/resources/inventory-rollback-plus-1-8-1-18-x.85811/)

**Comment by orang3i** [comment]
> This project seems to be abandoned. However, there is an updated fork available [here](https://www.spigotmc.org/resources/inventory-rollback-plus-1-8-1-18-x.85811/)

thanks
